name: main

env:
  LANG: C.UTF-8

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write

jobs:
  # Follows https://github.com/haskell-actions/setup#model-cabal-workflow-with-caching
  build-and-deploy:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ghc-version: ['9.6.6']
        cabal-version: ['3.12.1.0']
    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}
          cabal-update: true

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build all --dry-run
          # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: steps.cache.outputs.cache-hit != 'true'
        run: cabal build all --only-dependencies

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: actions/cache/save@v4
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all

      - name: Check cabal file
        run: cabal check

      # - name: Build documentation
      #   run: cabal haddock all
      #

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: spex-lang
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker pull
        run: docker pull ghcr.io/spex-lang/static-build:latest 

      - name: Build static binary
        run: |
          cd release && \
          docker run \
            -v "${PWD}/..":/mnt/:ro \
            -v "~/.cabal/packages":/root/.cache/cabal/packages \
            -v "~/.cabal/store":/root/.local/state/cabal/store \
            -v "${PWD}/dist-newstyle":/mnt/dist-newstyle \
            ghcr.io/spex-lang/static-build:latest

      # - name: Create new git tag, if merge to main and .cabal version is bumped
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   uses: sol/haskell-autotag@v1
      #   id: autotag

      # - name: Create tarball
      #   run: cabal sdist
      #   if: steps.autotag.outputs.created

      # - uses: haskell-actions/hackage-publish@v1.1
      #   with:
      #     # http://hackage.haskell.org/users/account-management
      #     hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
      #     publish: true
      #   if: steps.autotag.outputs.created
