name: main

env:
  LANG: C.UTF-8
  GH_TOKEN: ${{ github.token }}

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ghc-version: ['9.6.6']
        cabal-version: ['3.12.1.0']
    steps:
      - uses: actions/checkout@v4

      # Following https://github.com/docker/build-push-action?tab=readme-ov-file#usage
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: ${{ github.event_name != 'pull_request' }} # Don't push on PRs.
          tags: spex-lang/spex-build:latest
          # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .

      ##      - name: Docker pull
      ##        run: docker pull ghcr.io/spex-lang/spex-build:latest
      ##
      ##      - name: Docker build
      ##        run: docker build --tag ghcr.io/spex-lang/spex-build:latest .
      ##
      ##      - name: Docker push
      ##        if: ${{ github.event_name != 'pull_request' }} # Don't push on PRs.
      ##        run: docker push ghcr.io/spex-lang/spex-build:latest
      ##

